# Generated by Django 4.0.1 on 2022-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='std',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_fname', models.CharField(max_length=10)),
                ('std_lname', models.CharField(max_length=10)),
                ('std_email', models.EmailField(max_length=254, unique=True)),
                ('std_gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
